name: Village-Defense-Clan-Stats
version: ${project.version}
author: Simonsator
depends: [ Clans ]
depend: [ Clans ]
main: de.simonsator.partyandfriends.clan.stats.villagedefense.SPStatMain
description: Provides stats for Clans for Village Defense